// Generated by GraphWalker (http://www.graphwalker.org)
package es.udc.vvs.testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "es/udc/vvs/testautomation/Servidor.graphml")
public interface Servidor {

    @Vertex()
    void Ready();

    @Vertex()
    void Servidor_con_contenido();

    @Edge()
    void eliminar();

    @Vertex()
    void Servidor_con_contenido_y_token();

    @Edge()
    void alta();

    @Edge()
    void baja();

    @Vertex()
    void Servidor_con_token();

    @Edge()
    void agregar();

    @Edge()
    void iniciar_servidor();
}
